[tool.poetry]
name = "python playground"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
requests = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
